### ISSUE TITLE
代码有问题，特征把标签也算进去了。。。

### ISSUE THREAD

**Issue by fire717** [miaomiao3/tensorflow_fm#1]
作者你好，感谢开源，但是没觉得你的效果好的反常吗。。。训练集loss一直0.5几，第四个epoch验证集loss居然就只有0.0几了。。。研究半天发现，同样的数据我自己读的话id和item加起来应该只有2625种，你这却是2626种。。。。原因是你处理训练特征的时候没有drop掉rating，导致标签也在训练特征中（照着答案考试成绩不好才怪呢）。。。把rating去掉后再构造one-hot特征训练。。。效果就符合预期的很差了。。。

**Comment by miaomiao3** [comment]
是的，把结果drop掉之后才能onehot，谢谢
#2
